### ISSUE TITLE
Error after upgrading PHP to 7.4.12

### ISSUE THREAD

**Issue by maartenmachiels** [inetis-ch/oc-richeditorsnippets-plugin#15]
Hi, 

I just upgraded my xampp installation to the newest version of PHP, namely 7.4.12, after which I get the following error in sites that use the Richeditor Snippets plugin:

```
Trying to access array offset on value of type null
E:\Dropbox\Projects\_xampp\htdocs\georges\plugins\inetis\richeditorsnippets\classes\SnippetLoader.php line 167
```

If I comment out that line, the sites work perfectly. Do you think it's possible that there's an incompatibility?

Thanks for your work on this plugin by the way, it's very useful.

**Comment by Fl0Cri** [comment]
Hello, thanks for using our plugin.

I just did a quick test on PHP 7.4.12 and it seems to work fine.
What version of October are you using ? I tested on build 469. Or are you trying the October version with the Laravel 6 update ?

**Comment by maartenmachiels** [comment]
Hi, I'm also on version 469. Please note that when I updated my Xampp, the base url of my projects also moved (in this case from localhost:8080/georges to localhost/georges). I did change the application url in the config/app.php file, and when I disable the plugin, the site works. I've also just tried to uninstall and reïnstall the plugin, but it throws the same error. How weird is that?

**Comment by maartenmachiels** [comment]
FYI: I think the problem appears when migrating to another domain... I've seen it in other installs too that I migrate from my development machine to a test or production environment.

**Comment by Fl0Cri** [comment]
Sorry for the late reply (thank you for the update btw). I still cannot manage to reproduce the issue but I doubt it's because of php 7.4. It is more probably a problem with moving a site as you pointed out.

I did some digging and it looks realy wierd: after calling this https://github.com/inetis-ch/oc-richeditorsnippets-plugin/blob/master/classes/SnippetLoader.php#L167 `$page` **cannot** be null (it is null only if the page doesn't exist and in this case the plugin would not run).

The only reason I can find is that there's something wrong with the CmsController which returns a broken controller instance. But again, I cannot tell what could cause that.

Anyway, I've found an other way to get the CMS Page. Could you try to apply this commit 853e8a916749fc3bc535603344630f37b3960465 or pull the `dev` branch and tell me if it fixes the problem ?

**Comment by maartenmachiels** [comment]
Hi, sorry for the late reply. I just tested this out and this does indeed fix it. Thanks for your work!
