### ISSUE TITLE
Plugin doesn't work with October 3

### ISSUE THREAD

**Issue by ssi-com-pl** [inetis-ch/oc-richeditorsnippets-plugin#22]
Hi! It seems that this plugin doesn't work with October 3.
I can no longer add snippets to "CMS Content File".
![image](https://user-images.githubusercontent.com/57666038/226944281-9413a1bd-be5a-441b-89b6-5ee569dd3bb4.png)

Same with plugin richeditor fields:
![image](https://user-images.githubusercontent.com/57666038/226944846-7a418d88-abf5-4388-9922-c449c68f1339.png)

**UPDATE**
I've added "snippets" here:
![image](https://user-images.githubusercontent.com/57666038/226955704-51581594-e242-445f-a767-9916905d50cd.png)
But something still doesn't work:
![image](https://user-images.githubusercontent.com/57666038/226945450-2ff084c1-5896-4451-8004-649f9b373e6f.png)

**Comment by Fl0Cri** [comment]
Hi, the problem is that the `filter` tag has been deprecated in Twig 2 and removed in Twig 3 (https://twig.symfony.com/doc/2.x/tags/filter.html). You can use the `apply` tag instead like so:

```twig
{% apply parseSnippets %}
    {% content 'test.htm' %}
{% endapply %}
```

I have updated the documentation in the readme.md as well as in the marketplace to reflect this (latest version of October 1 also support the `apply` tag, so I replaced all occurences of `{% filter %}`).
