### ISSUE TITLE
Support for rainlab blog with janvince.smallextensions

### ISSUE THREAD

**Issue by xkapr** [inetis-ch/oc-richeditorsnippets-plugin#9]
Hi, i have Rainlab.Blog and janvince.smallextensions installed. I want to use richeditor snippets extension in blog editing. The snippets menu appears in richeditor menu while blog post editing. It also inserts the snippet. But the snippet is broken when save and reopen. And does not appear on live site.
It is possibility to implement this functionallity?

**Comment by Fl0Cri** [comment]
Hi, finally got some time to work on this.

There was a problem with snippets initialization on Rainlab.Blog (and anywhere else with a richeditor initialized on page load) making snippets to look broken.

I will release v2.1.1 on monday, it should fix this issue.

But there is still someting that you need to do on your site in order to make the snippets show up: in your CMS page, surround the `blogPost` component with the `parseSnippets` filter like this:
```
{% filter parseSnippets %}
    {% component 'blogPost' %}
{% endfilter %}
```
